
package com.georgexie.weather;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WeatherInterfaceImpl", targetNamespace = "http://weather.georgexie.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WeatherInterfaceImpl {


    /**
     * 
     * @param cityName
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getWeather", targetNamespace = "http://weather.georgexie.com/", className = "com.georgexie.weather.GetWeather")
    @ResponseWrapper(localName = "getWeatherResponse", targetNamespace = "http://weather.georgexie.com/", className = "com.georgexie.weather.GetWeatherResponse")
    @Action(input = "http://weather.georgexie.com/WeatherInterfaceImpl/getWeatherRequest", output = "http://weather.georgexie.com/WeatherInterfaceImpl/getWeatherResponse")
    public String getWeather(
        @WebParam(name = "cityName", targetNamespace = "")
        String cityName);

}
